version: "3.7"
services:
  nexus:
    image: sonatype/nexus3
    expose:
      - 8081
      - 8082
      - 8083
    restart: always
    volumes:
      - "nexus-work:/sonatype-work"
    ports:
      - "5001:8081"
      - "5002:8082"
      - "5003:8083"
volumes:
  nexus-work: {}
